# Generated by Django 5.0.3 on 2024-04-12 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BicyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run", models.PositiveIntegerField(verbose_name="RUN")),
            ],
        ),
        migrations.CreateModel(
            name="Bicycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=100, verbose_name="Bicycle model"),
                ),
                (
                    "colour",
                    models.CharField(max_length=100, verbose_name="Bicycle color"),
                ),
                (
                    "bike_type",
                    models.CharField(
                        choices=[
                            ("RB", "Road Bike"),
                            ("CCB", "Cyclo-cross Bike"),
                            ("GB", "Grave Bike"),
                            ("TTB", "Time Trial Bike"),
                            ("TB", "Touring Bike"),
                            ("FB", "Folding Bike"),
                            ("BMX", "BMX"),
                            ("EB", "Electric Bike"),
                        ],
                        default="RB",
                        max_length=3,
                    ),
                ),
                (
                    "bicy_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bicyuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BicycleHolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Capacity"
                    ),
                ),
                ("location", models.CharField(max_length=30, verbose_name="Location")),
                (
                    "nearest_building",
                    models.CharField(
                        choices=[
                            ("K", "K"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("E", "E"),
                        ],
                        max_length=1,
                        verbose_name="Nearest building",
                    ),
                ),
                (
                    "nearest_guard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.guard"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KeyChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.PositiveBigIntegerField(
                        default=None, null=True, verbose_name="UUID"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bicyuser"
                    ),
                ),
            ],
        ),
    ]
