# Generated by Django 5.0.3 on 2024-04-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="run",
            field=models.PositiveBigIntegerField(
                error_messages={"unique": "Ese RUN ya se encuentra registrado."},
                null=True,
                unique=True,
                verbose_name="RUN",
            ),
        ),
    ]
