# Generated by Django 5.0.3 on 2024-04-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_guard",
            field=models.BooleanField(default=False),
        ),
    ]
