# Generated by Django 5.0.3 on 2024-04-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_is_guard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academic",
            name="connection",
            field=models.CharField(
                default=None, max_length=100, null=True, verbose_name="Conexión con USM"
            ),
        ),
        migrations.AlterField(
            model_name="external",
            name="connection",
            field=models.CharField(
                default=None, max_length=100, null=True, verbose_name="Conexión con USM"
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="department",
            field=models.CharField(
                default=None, max_length=20, null=True, verbose_name="Departamento"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="charge",
            field=models.CharField(
                default=None, max_length=40, null=True, verbose_name="Cargo en USM"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="career",
            field=models.CharField(
                default=None, max_length=20, null=True, verbose_name="Carrera"
            ),
        ),
    ]
