# Generated by Django 5.0.3 on 2024-04-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_student_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academic",
            options={"verbose_name": "Academico", "verbose_name_plural": "Academicos"},
        ),
        migrations.AlterModelOptions(
            name="external",
            options={"verbose_name": "Externo", "verbose_name_plural": "Externos"},
        ),
        migrations.AlterModelOptions(
            name="professor",
            options={"verbose_name": "Profesor", "verbose_name_plural": "Profesores"},
        ),
        migrations.AlterModelOptions(
            name="staff",
            options={"verbose_name": "Staff", "verbose_name_plural": "Staffs"},
        ),
    ]
