# Generated by Django 5.0.3 on 2024-04-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_academic_options_alter_external_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guard",
            options={"verbose_name": "Guardia", "verbose_name_plural": "Guardias"},
        ),
    ]
