# Generated by Django 5.0.6 on 2024-06-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyticket',
            name='message',
            field=models.TextField(default=None, max_length=500, verbose_name='Message'),
        ),
    ]
