# Generated by Django 5.0.6 on 2024-06-23 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_bicycleholder_coord_x_and_more'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registryticket',
            name='user',
        ),
        migrations.AlterField(
            model_name='registryticket',
            name='keychain',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.keychain'),
        ),
    ]
