# Generated by Django 5.0.6 on 2024-06-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_registryticket_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryticket',
            name='solved',
            field=models.BooleanField(default=False, verbose_name='Solved?'),
        ),
    ]
